/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LandlordRouteImport } from './routes/_landlord'
import { Route as HousesIndexRouteImport } from './routes/houses.index'
import { Route as HousesIdRouteImport } from './routes/houses.$id'
import { Route as LandlordLoginRouteImport } from './routes/landlord.login'
import { Route as LandlordRegisterRouteImport } from './routes/landlord.register'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminLandlordsRouteImport } from './routes/_admin/admin.landlords'
import { Route as AdminAdminListingsRouteImport } from './routes/_admin/admin.listings'
import { Route as LandlordLandlordDashboardRouteImport } from './routes/_landlord/landlord.dashboard'
import { Route as LandlordLandlordProfileRouteImport } from './routes/_landlord/landlord.profile'
import { Route as LandlordLandlordListingsIndexRouteImport } from './routes/_landlord/landlord.listings.index'
import { Route as LandlordLandlordListingsNewRouteImport } from './routes/_landlord/landlord.listings.new'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as LandlordLandlordListingsIdEditRouteImport } from './routes/_landlord/landlord.listings.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/_landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordLoginRoute = LandlordLoginRouteImport.update({
  id: '/landlord/login',
  path: '/landlord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRegisterRoute = LandlordRegisterRouteImport.update({
  id: '/landlord/register',
  path: '/landlord/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLandlordsRoute = AdminAdminLandlordsRouteImport.update({
  id: '/admin/landlords',
  path: '/admin/landlords',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminListingsRoute = AdminAdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => AdminRoute,
} as any)
const LandlordLandlordDashboardRoute =
  LandlordLandlordDashboardRouteImport.update({
    id: '/landlord/dashboard',
    path: '/landlord/dashboard',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordProfileRoute = LandlordLandlordProfileRouteImport.update({
  id: '/landlord/profile',
  path: '/landlord/profile',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordLandlordListingsIndexRoute =
  LandlordLandlordListingsIndexRouteImport.update({
    id: '/landlord/listings/',
    path: '/landlord/listings/',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordListingsNewRoute =
  LandlordLandlordListingsNewRouteImport.update({
    id: '/landlord/listings/new',
    path: '/landlord/listings/new',
    getParentRoute: () => LandlordRoute,
  } as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordLandlordListingsIdEditRoute =
  LandlordLandlordListingsIdEditRouteImport.update({
    id: '/landlord/listings/$id/edit',
    path: '/landlord/listings/$id/edit',
    getParentRoute: () => LandlordRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses/$id': typeof HousesIdRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/landlord/register': typeof LandlordRegisterRoute
  '/houses/': typeof HousesIndexRoute
  '/admin/landlords': typeof AdminAdminLandlordsRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/landlord/profile': typeof LandlordLandlordProfileRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/landlord/listings/new': typeof LandlordLandlordListingsNewRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/landlord/listings/': typeof LandlordLandlordListingsIndexRoute
  '/landlord/listings/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houses/$id': typeof HousesIdRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/landlord/register': typeof LandlordRegisterRoute
  '/houses': typeof HousesIndexRoute
  '/admin/landlords': typeof AdminAdminLandlordsRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/landlord/profile': typeof LandlordLandlordProfileRoute
  '/admin': typeof AdminAdminIndexRoute
  '/landlord/listings/new': typeof LandlordLandlordListingsNewRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/landlord/listings': typeof LandlordLandlordListingsIndexRoute
  '/landlord/listings/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_landlord': typeof LandlordRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/landlord/register': typeof LandlordRegisterRoute
  '/houses/': typeof HousesIndexRoute
  '/_admin/admin/landlords': typeof AdminAdminLandlordsRoute
  '/_admin/admin/listings': typeof AdminAdminListingsRoute
  '/_landlord/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/_landlord/landlord/profile': typeof LandlordLandlordProfileRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_landlord/landlord/listings/new': typeof LandlordLandlordListingsNewRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/_landlord/landlord/listings/': typeof LandlordLandlordListingsIndexRoute
  '/_landlord/landlord/listings/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/houses/$id'
    | '/landlord/login'
    | '/landlord/register'
    | '/houses/'
    | '/admin/landlords'
    | '/admin/listings'
    | '/landlord/dashboard'
    | '/landlord/profile'
    | '/admin/'
    | '/landlord/listings/new'
    | '/api/public/img/$'
    | '/landlord/listings/'
    | '/landlord/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/houses/$id'
    | '/landlord/login'
    | '/landlord/register'
    | '/houses'
    | '/admin/landlords'
    | '/admin/listings'
    | '/landlord/dashboard'
    | '/landlord/profile'
    | '/admin'
    | '/landlord/listings/new'
    | '/api/public/img/$'
    | '/landlord/listings'
    | '/landlord/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_landlord'
    | '/houses/$id'
    | '/landlord/login'
    | '/landlord/register'
    | '/houses/'
    | '/_admin/admin/landlords'
    | '/_admin/admin/listings'
    | '/_landlord/landlord/dashboard'
    | '/_landlord/landlord/profile'
    | '/_admin/admin/'
    | '/_landlord/landlord/listings/new'
    | '/api/public/img/$'
    | '/_landlord/landlord/listings/'
    | '/_landlord/landlord/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LandlordRoute: typeof LandlordRouteWithChildren
  HousesIdRoute: typeof HousesIdRoute
  LandlordLoginRoute: typeof LandlordLoginRoute
  LandlordRegisterRoute: typeof LandlordRegisterRoute
  HousesIndexRoute: typeof HousesIndexRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landlord': {
      id: '/_landlord'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/login': {
      id: '/landlord/login'
      path: '/landlord/login'
      fullPath: '/landlord/login'
      preLoaderRoute: typeof LandlordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/register': {
      id: '/landlord/register'
      path: '/landlord/register'
      fullPath: '/landlord/register'
      preLoaderRoute: typeof LandlordRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/landlords': {
      id: '/_admin/admin/landlords'
      path: '/admin/landlords'
      fullPath: '/admin/landlords'
      preLoaderRoute: typeof AdminAdminLandlordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/listings': {
      id: '/_admin/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminAdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_landlord/landlord/dashboard': {
      id: '/_landlord/landlord/dashboard'
      path: '/landlord/dashboard'
      fullPath: '/landlord/dashboard'
      preLoaderRoute: typeof LandlordLandlordDashboardRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/profile': {
      id: '/_landlord/landlord/profile'
      path: '/landlord/profile'
      fullPath: '/landlord/profile'
      preLoaderRoute: typeof LandlordLandlordProfileRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/listings/': {
      id: '/_landlord/landlord/listings/'
      path: '/landlord/listings'
      fullPath: '/landlord/listings/'
      preLoaderRoute: typeof LandlordLandlordListingsIndexRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/listings/new': {
      id: '/_landlord/landlord/listings/new'
      path: '/landlord/listings/new'
      fullPath: '/landlord/listings/new'
      preLoaderRoute: typeof LandlordLandlordListingsNewRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landlord/landlord/listings/$id/edit': {
      id: '/_landlord/landlord/listings/$id/edit'
      path: '/landlord/listings/$id/edit'
      fullPath: '/landlord/listings/$id/edit'
      preLoaderRoute: typeof LandlordLandlordListingsIdEditRouteImport
      parentRoute: typeof LandlordRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminLandlordsRoute: typeof AdminAdminLandlordsRoute
  AdminAdminListingsRoute: typeof AdminAdminListingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLandlordsRoute: AdminAdminLandlordsRoute,
  AdminAdminListingsRoute: AdminAdminListingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LandlordRouteChildren {
  LandlordLandlordDashboardRoute: typeof LandlordLandlordDashboardRoute
  LandlordLandlordProfileRoute: typeof LandlordLandlordProfileRoute
  LandlordLandlordListingsNewRoute: typeof LandlordLandlordListingsNewRoute
  LandlordLandlordListingsIndexRoute: typeof LandlordLandlordListingsIndexRoute
  LandlordLandlordListingsIdEditRoute: typeof LandlordLandlordListingsIdEditRoute
}

const LandlordRouteChildren: LandlordRouteChildren = {
  LandlordLandlordDashboardRoute: LandlordLandlordDashboardRoute,
  LandlordLandlordProfileRoute: LandlordLandlordProfileRoute,
  LandlordLandlordListingsNewRoute: LandlordLandlordListingsNewRoute,
  LandlordLandlordListingsIndexRoute: LandlordLandlordListingsIndexRoute,
  LandlordLandlordListingsIdEditRoute: LandlordLandlordListingsIdEditRoute,
}

const LandlordRouteWithChildren = LandlordRoute._addFileChildren(
  LandlordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LandlordRoute: LandlordRouteWithChildren,
  HousesIdRoute: HousesIdRoute,
  LandlordLoginRoute: LandlordLoginRoute,
  LandlordRegisterRoute: LandlordRegisterRoute,
  HousesIndexRoute: HousesIndexRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
